<?php
# Generated by the protocol buffer compiler (mix/grpc). DO NOT EDIT!
# source: simple/simple.proto

namespace TestSimple;

use Mix\Grpc;

interface SimpleServiceInterface extends Grpc\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "testSimple.SimpleService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param SimpleMessage $in
    * @return SimpleMessage
    *
    * @throws Grpc\Exception\InvokeException
    */
    public function SimpleMethod(Grpc\ContextInterface $ctx, SimpleMessage $in): SimpleMessage;
}
