<?php

namespace apps\daemon\commands;

use mix\console\ExitCode;
use mix\facades\Input;

/**
 * 协程范例
 * @author 刘健 <coder.liu@qq.com>
 */
class CoroutineCommand extends BaseCommand
{

    // 初始化事件
    public function onInitialize()
    {
        parent::onInitialize(); // TODO: Change the autogenerated stub
        // 获取程序名称
        $this->programName = Input::getCommandName();
        // 设置pidfile
        $this->pidFile = "/var/run/{$this->programName}.pid";
    }

    // 启动
    public function actionStart()
    {
        // 预处理
        if (!parent::actionStart()) {
            return ExitCode::UNSPECIFIED_ERROR;
        }
        // 开始工作
        $this->startWork();
        // 返回退出码
        return ExitCode::OK;
    }

    // 开始工作
    public function startWork()
    {
        for ($i = 0; $i < 200; $i++) {
            tgo(function () {
                $pdo    = \mix\coroutine\PDO::newInstanceByConfig('pdo');
                $result = $pdo->createCommand('select sleep(2)')->queryAll();
                var_dump($result);
            });
        }
    }

}
