<?php

namespace index\controller;

use mix\web\Controller;

/**
 * 默认控制器
 * @author 刘健 <coder.liu@qq.com>
 */
class IndexController extends Controller
{

    public function onInitialize()
    {
        parent::onInitialize(); // TODO: Change the autogenerated stub
        \Mix::finish();
    }

    public function actionIndex()
    {
        return 'Hello World' . PHP_EOL;
    }

}
