<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greeter.proto

namespace GPBMetadata;

class Greeter
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab6010a0d677265657465722e70726f746f12167068702e6d6963726f2e677270632e6772656574657222170a0752657175657374120c0a046e616d6518012001280922170a08526573706f6e7365120b0a036d736718012001280932530a03536179124c0a0548656c6c6f121f2e7068702e6d6963726f2e677270632e677265657465722e526571756573741a202e7068702e6d6963726f2e677270632e677265657465722e526573706f6e73652200620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

