<?php

namespace apps\crontab\commands;

use mix\console\Command;
use mix\console\ExitCode;
use mix\facades\Input;
use mix\facades\Output;
use mix\task\TaskExecutor;

/**
 * 这是一个多进程定时任务的范例，任务执行完成就会自动结束进程
 * 进程模型为：生产者消费者模型
 * 你可以自由选择是左进程当生产者还是右进程当生产者，本范例是左进程当生产者
 * @author 刘健 <coder.liu@qq.com>
 */
class MultiCommand extends Command
{

    // 是否后台运行
    public $daemon = false;

    // 程序名称
    protected $programName = '';

    // 选项配置
    public function options()
    {
        return ['daemon'];
    }

    // 选项别名配置
    public function optionAliases()
    {
        return ['d' => 'daemon'];
    }

    // 初始化事件
    public function onInitialize()
    {
        parent::onInitialize(); // TODO: Change the autogenerated stub
        // 获取程序名称
        $this->programName = Input::getCommandName();
    }

    /**
     * 获取服务
     * @return TaskExecutor
     */
    public function getTaskService()
    {
        return \Mix::createObject(
            [
                // 类路径
                'class'        => 'mix\task\TaskExecutor',
                // 左进程数
                'leftProcess'  => 1,
                // 右进程数
                'rightProcess' => 3,
                // 服务名称
                'name'         => "mix-crontab: {$this->programName}",
                // 进程队列的key
                'queueKey'     => __FILE__ . uniqid(),
            ]
        );
    }

    // 执行任务
    public function actionExec()
    {
        // 启动提示
        Output::writeln("mix-crontab '{$this->programName}' start successed.");
        // 蜕变为守护进程
        if ($this->daemon) {
            Process::daemon();
        }
        // 启动服务
        $service = $this->getTaskService();
        $service->on('LeftStart', [$this, 'onLeftStart']);
        $service->on('RightStart', [$this, 'onRightStart']);
        $service->start();
        // 返回退出码
        return ExitCode::OK;
    }

    // 左进程启动事件回调函数
    public function onLeftStart(TaskProcess $worker, $index)
    {
        // 模型内使用短连接版本的数据库组件，计划任务都是一次性执行
        $tableModel = new \apps\common\models\TableModel();
        // 将结果集一行一行发送给消费者进程
        foreach ($tableModel->getAll() as $item) {
            // 将消息推送给消费者进程去处理，push有长度限制：https://wiki.swoole.com/wiki/page/290.html
            $worker->push(serialize($item));
        }
        // 发送完后杀死主进程，这样消费者进程处理完进程队列里的数据就会自动退出
        $worker->killMaster();
    }

    // 右进程启动事件回调函数
    public function onRightStart(TaskProcess $worker, $index)
    {
        // 循环执行任务
        for ($j = 0; $j < 16000; $j++) {
            $worker->checkMaster();
            // 从进程队列中抢占一条消息
            $msg = $worker->pop();
            $msg = unserialize($msg);
            if (!empty($msg)) {
                // 处理消息，比如：发送短信、发送邮件、微信推送
                // ...
            }
        }
    }

}
