<?php

namespace Console\Commands;

use Mix\Console\CommandLine\Arguments;
use Mix\Console\CommandLine\Color;
use Mix\Core\Channel;
use Mix\Core\ChannelHook;

/**
 * 协程范例
 * @author 刘健 <coder.liu@qq.com>
 */
class CoroutineCommand extends BaseCommand
{

    // 初始化事件
    public function onInitialize()
    {
        parent::onInitialize(); // TODO: Change the autogenerated stub
        // 获取程序名称
        $this->programName = Arguments::command();
        // 设置pidfile
        $this->pidFile = "/var/run/{$this->programName}.pid";
    }

    // 执行
    public function main()
    {
        Color::new(Color::BG_HI_RED)->println("                ");
    }

    // 查询数据
    public function foo()
    {
        $chan = new Channel();
        tgo(function (ChannelHook $hook) use ($chan) {
            // 安装钩子
            $hook->install($chan);
            // 子协程内只可使用局部变量，而组件为全局变量是不可以在子协程内使用的，会导致内存溢出，所以使用组件配置动态实例化
            $pdo    = app()->pdoPool->getConnection();
            $result = $pdo->createCommand('select sleep(2)')->queryAll();
            $chan->push($result);
        });
        return $chan;
    }

    // 查询数据
    public function bar()
    {
        $chan = new Channel();
        tgo(function (ChannelHook $hook) use ($chan) {
            // 安装钩子
            $hook->install($chan);
            // 子协程内只可使用局部变量，而组件为全局变量是不可以在子协程内使用的，会导致内存溢出，所以使用组件配置动态实例化
            $pdo    = app()->pdoPool->getConnection();
            $result = $pdo->createCommand('select sleep(1)')->queryAll();
            $chan->push($result);
        });
        return $chan;
    }

}
